const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const js=fs.readFileSync(path.join(__dirname,'../Rotepad.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(js);
const c={};vm.createContext(c);
vm.runInContext(js.slice(js.indexOf('function validateBackup'),js.indexOf('function exportBackup')),c);
const data={format:'rotepad-backup',version:1,notes:[{name:'Pinned.md',text:'**Hello**',pinned:true,revisions:[{text:'Old',name:'Pinned.md',at:123}]},{name:'Deleted.md',text:'Recover me',trashed:true}],prefs:{theme:'dark',zoom:'125',spellcheck:false}};
const restored=c.validateBackup(JSON.parse(JSON.stringify(data)));
assert.equal(restored.notes.length,2);
assert.equal(restored.notes[0].pinned,true);
assert.equal(restored.notes[1].trashed,true);
assert.equal(restored.notes[0].revisions[0].text,'Old');
assert.equal(restored.notes[0].text,'**Hello**');
assert.throws(()=>c.validateBackup({notes:[]}),/Rotepad backup/);
assert.throws(()=>c.validateBackup({...data,notes:[{name:'Bad.md',text:42}]}),/invalid note/);
assert.throws(()=>c.validateBackup({...data,notes:Array(10001).fill(data.notes[0])}),/too many/);
assert.equal(c.restoredPrefs(data.prefs).zoom,'125');
assert.equal(c.restoredPrefs(data.prefs).spellcheck,false);
assert.equal(c.restoredPrefs({zoom:'999',theme:'unknown'}).zoom,'100');
assert.equal(c.restoredPrefs({zoom:'999',theme:'unknown'}).theme,'system');
assert.equal(c.restoredPrefs({}).spellcheck,true);
assert.equal(data.notes[0].revisions.length,1,'validation does not mutate original notes');
console.log('14 backup validation, Trash/pin preservation, and settings checks passed.');
