const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const js=fs.readFileSync(path.join(__dirname,'../Rotepad.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(js);
const c={URL,prefs:{sort:'name'}};vm.createContext(c);
for(const [start,end] of [['function compareNotes',"$('notes-search').insertAdjacentHTML('afterend'"],['function headingEntries','function renderOutline'],['function textSignature','function updateFileStatus'],['function pastedWebsite',"rich.addEventListener('paste',e=>{const selection"],['function safeURL','function inline']])vm.runInContext(js.slice(js.indexOf(start),js.indexOf(end,js.indexOf(start))),c);
assert.ok(c.compareNotes({name:'Z',pinned:true},{name:'A'})<0);
assert.ok(c.compareNotes({name:'Alpha'},{name:'Beta'})<0);
c.prefs.sort='newest';assert.ok(c.compareNotes({created:20},{created:10})<0);
c.prefs.sort='updated';assert.ok(c.compareNotes({updated:20},{updated:10})<0);
const headings=c.headingEntries('# One\ntext\n```\n# code\n```\n## Two');
assert.equal(headings.length,2);assert.equal(headings[1].level,2);
assert.equal(headings[1].offset,'# One\ntext\n```\n# code\n```\n'.length);
assert.equal(c.textSignature('note'),c.textSignature('note'));
assert.notEqual(c.textSignature('note'),c.textSignature('note edited'));
assert.equal(c.pastedWebsite(' www.facebook.com '),'https://www.facebook.com/');
assert.equal(c.pastedWebsite('https://example.com'),'https://example.com/');
assert.equal(c.pastedWebsite('javascript:alert(1)'),null);
assert.equal(c.pastedWebsite('not a website'),null);
console.log('13 sorting, heading outline, file signature, and paste-link checks passed.');
