const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const js=fs.readFileSync(path.join(__dirname,'../Rotepad.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(js);
let now=1000000;const c={URL,Date:{now:()=>now}};vm.createContext(c);
for(const [start,end] of [['function safeURL','function inline'],['function websiteURL',"$('link-url').type"],['function changedCharacters','let savepointReason'],['function addRevision','function captureState']])vm.runInContext(js.slice(js.indexOf(start),js.indexOf(end,js.indexOf(start))),c);
assert.equal(c.websiteURL('facebook.com'),'https://facebook.com/');
assert.equal(c.websiteURL('www.facebook.com'),'https://www.facebook.com/');
assert.equal(c.websiteURL('example.com/path?q=yes'),'https://example.com/path?q=yes');
assert.equal(c.websiteURL('https://example.com'),'https://example.com/');
for(const url of ['javascript:alert(1)','data:text/html,test','bad address','person@example.com','not-a-site'])assert.equal(c.websiteURL(url),null);
assert.equal(c.significantEdit('a'.repeat(100),'b'.repeat(100)),true,'same-length rewrites count');
assert.equal(c.significantEdit('long text','long text!'),false);
assert.equal(c.significantEdit('a'.repeat(50),'a'.repeat(20)),true,'large relative deletion counts');
const note={name:'test.md',text:'',revisions:[]};c.addRevision(note,'','test.md','Before paste');c.addRevision(note,'new passage','test.md','Pasted text');assert.equal(note.revisions.length,1);
now+=179999;c.addRevision(note,'x'.repeat(100),'test.md','Pasted text');assert.equal(note.revisions.length,1);
now+=1;c.addRevision(note,'x'.repeat(100),'test.md','Pasted text');
assert.equal(note.revisions.length,2);assert.equal(note.revisions[0].text,'');assert.equal(note.revisions[1].reason,'Pasted text');
c.addRevision(note,'x'.repeat(100),'test.md','Duplicate');assert.equal(note.revisions.length,2);
now+=180000;c.addRevision(note,'x'.repeat(100)+'!','test.md','Automatic savepoint');assert.equal(note.revisions.length,2,'minor edits do not fill history even after cooldown');
console.log('Website normalization and major-edit savepoint checks passed.');
