const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../Rotepad.html')).href);
 assert.equal(await page.locator('#editing-mode').innerText(),'Formatted');
 await page.locator('#rich-editor').click();await page.keyboard.type('**literal**');assert.equal(await page.locator('#rich-editor strong').count(),0);
 await page.keyboard.press('Enter');await page.keyboard.type('next');assert.equal(await page.evaluate(()=>editor.value),'\\*\\*literal\\*\\*\nnext');
 await page.locator('#editing-mode').click();assert.equal(await page.locator('#editing-mode').innerText(),'Markdown');await page.locator('#editor').fill('**bold**');await page.locator('#editing-mode').click();assert.equal(await page.locator('#rich-editor strong').innerText(),'bold');
 await page.evaluate(()=>{createNote('Manual.md','');rich.focus();});await page.keyboard.press('Control+b');await page.keyboard.type('manual');await page.keyboard.press('Control+b');await page.keyboard.type(' normal');assert.equal(await page.locator('#rich-editor b,#rich-editor strong').innerText(),'manual');
 await page.evaluate(()=>{const r=document.createRange();r.selectNodeContents(rich);getSelection().removeAllRanges();getSelection().addRange(r);rememberRange();updateFormatting();$('clear-format').click();});assert.equal(await page.locator('#rich-editor b,#rich-editor strong').count(),0);
 await page.evaluate(()=>{$('insert-table').click();});await page.locator('#table-form button[type=submit]').click();assert.equal(await page.locator('#rich-editor table').count(),1);
 await page.locator('#rich-editor th').first().fill('Name | label');await page.locator('#rich-editor td').first().fill('Value');
 const tableMarkdown=await page.evaluate(()=>editor.value);assert.ok(tableMarkdown.includes('Name \\| label'));
 await page.locator('#editing-mode').click();await page.locator('#editing-mode').click();assert.equal(await page.locator('#rich-editor th').first().innerText(),'Name | label');assert.equal(await page.locator('#rich-editor td').first().innerText(),'Value');
 await page.locator('#rich-editor td').last().click();await page.keyboard.press('Tab');assert.equal(await page.locator('#rich-editor table tr').count(),4);
 await page.evaluate(()=>{createNote('Paragraph.md','text');setMode('rich');rich.focus();placeCaret(0);rememberRange();indentSelection(false);});assert.equal(await page.evaluate(()=>editor.value),'\ttext');await page.evaluate(()=>loadRich());assert.equal(await page.locator('#rich-editor p').innerText(),'\ttext');
 await page.evaluate(()=>{createNote('Indent.md','- Parent\n- Child');setMode('rich');const li=rich.querySelectorAll('li')[1],r=document.createRange();r.selectNodeContents(li);r.collapse(true);getSelection().removeAllRanges();getSelection().addRange(r);rememberRange();indentSelection(false);});
 assert.ok(await page.evaluate(()=>editor.value.includes('\n    - Child')));await page.evaluate(()=>loadRich());assert.equal(await page.locator('#rich-editor li ul li').innerText(),'Child');
 await page.evaluate(()=>{createNote('Date.md','');rich.focus();});await page.keyboard.press('F5');assert.ok((await page.locator('#rich-editor').innerText()).length>8);
 await page.evaluate(()=>{prefs.autoMarkdown=true;persist();createNote('Optional.md','');rich.focus();});await page.keyboard.type('**yes** normal');assert.equal(await page.locator('#rich-editor strong').innerText(),'yes');
 await page.reload();assert.equal(await page.locator('#editing-mode').innerText(),'Formatted');assert.equal(await page.evaluate(()=>prefs.autoMarkdown),true);
 assert.deepEqual(errors,[]);console.log('Formatted defaults, literal typing, shortcuts, view switching, table pipe escaping/round trip, nested indentation, timestamp and preference persistence passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
