const {_electron:electron}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const profile=path.join(__dirname,'test-profile','reveal-'+Date.now());
let app;
(async()=>{
 await fs.mkdir(profile,{recursive:true});
 const folder=path.join(profile,'notes');
 await fs.writeFile(path.join(profile,'desktop-settings.json'),JSON.stringify({saveFolder:folder}),{flag:'wx'});
 app=await electron.launch({executablePath:require('electron'),args:[__dirname],env:{...process.env,ROTEPAD_TEST_DATA:profile}});
 const page=await app.firstWindow();await page.waitForFunction(()=>typeof flushLibrary==='function');
 assert.equal((await page.evaluate(()=>rotDesktop.settings())).saveFolder,folder);
 await app.evaluate(({shell})=>{global.revealed=[];shell.showItemInFolder=file=>global.revealed.push(file);});
 await page.evaluate(()=>{window.alert=message=>window.lastRevealAlert=message;});
 await page.evaluate(async()=>{manageNote(activeId);await $('note-show-in-folder').onclick();});
 assert.match(await page.evaluate(()=>window.lastRevealAlert),/no file yet/);
 assert.equal((await app.evaluate(()=>global.revealed)).length,0);
 const id=await page.evaluate(async()=>{$('note-actions-dialog').close();createNote('Reveal me','Pending text');filename.value='Renamed';editor.value='Latest edits';manageNote(activeId);await $('note-show-in-folder').onclick();return activeId;});
 let index=JSON.parse(await fs.readFile(path.join(profile,'managed-notes.json'),'utf8'));
 assert.equal((await app.evaluate(()=>global.revealed)).at(-1),index[id].file);
 assert.equal(path.basename(index[id].file),'Renamed.md');assert.equal(await fs.readFile(index[id].file,'utf8'),'Latest edits');
 assert.equal(await page.evaluate(()=>$('note-actions-dialog').open),false);
 await page.evaluate(async id=>{createNote('Other','Second');manageNote(id);await $('note-show-in-folder').onclick();},id);
 assert.equal((await app.evaluate(()=>global.revealed)).at(-1),index[id].file);
 await page.evaluate(async id=>{manageNote(id);$('note-trash').click();manageNote(id);await $('note-show-in-folder').onclick();},id);
 index=JSON.parse(await fs.readFile(path.join(profile,'managed-notes.json'),'utf8'));
 assert.equal(path.basename(path.dirname(index[id].file)),'.Trash');assert.equal((await app.evaluate(()=>global.revealed)).at(-1),index[id].file);
 await assert.rejects(page.evaluate(()=>rotDesktop.showInFolder('unknown-note')),/Note not found/);
 await fs.unlink(index[id].file);
 await assert.rejects(page.evaluate(id=>rotDesktop.showInFolder(id),id),/ENOENT/);
 console.log('PASS: reveal flushes edits/rename, resolves inactive and Trash notes, and handles empty, invalid and missing files. Explorer is mocked.');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(app)await app.close();});
