const {chromium,_electron}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const native=process.argv.includes('--desktop');let host,page;
async function fresh(text='',view='rich'){await page.evaluate(({text,view})=>{createNote('Tab test',text);setMode(view);(view==='rich'?rich:editor).focus();},{text,view});}
async function caret(text,offset=0){await page.evaluate(({text,offset})=>{rich.focus();const w=document.createTreeWalker(rich,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode())if(n.data.includes(text)){const r=document.createRange();r.setStart(n,n.data.indexOf(text)+offset);r.collapse(true);getSelection().removeAllRanges();getSelection().addRange(r);rememberRange();return;}throw Error('Missing '+text);},{text,offset});}
async function source(){return page.evaluate(()=>editor.value);}
(async()=>{
 if(native){const profile=path.join(__dirname,'test-profile','tabs-'+Date.now());await fs.mkdir(profile,{recursive:true});await fs.writeFile(path.join(profile,'desktop-settings.json'),JSON.stringify({saveFolder:path.join(profile,'notes')}),{flag:'wx'});host=await _electron.launch({executablePath:require('electron'),args:[__dirname],env:{...process.env,ROTEPAD_TEST_DATA:profile}});page=await host.firstWindow();await page.waitForFunction(()=>typeof flushLibrary==='function');}
 else{host=await chromium.launch({channel:'msedge',headless:true});page=await host.newPage();await page.goto(pathToFileURL(path.resolve(__dirname,'../Rotepad.html')).href);}
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await fresh();await page.keyboard.press('Tab');await page.keyboard.type('Text');assert.equal(await source(),'\tText');assert.equal(await page.evaluate(()=>document.activeElement===rich),true);
 await page.keyboard.press('Home');await page.keyboard.press('Shift+Tab');assert.equal(await source(),'Text');
 await fresh('AlphaBeta');await caret('Beta');await page.keyboard.press('Tab');await page.keyboard.type('X');assert.equal(await source(),'Alpha\tXBeta');
 await fresh('AB');await caret('B');await page.keyboard.press('Tab');assert.equal(await source(),'A\tB');await page.keyboard.press('Control+z');assert.equal(await source(),'AB');await page.keyboard.press('Control+y');assert.equal(await source(),'A\tB');
 await fresh('**Bold**');await caret('Bold',2);await page.keyboard.press('Tab');assert.equal(await page.locator('#rich-editor :is(strong,b)').innerText(),'Bo\tld');
 for(const prefix of ['- ','1. ']){await fresh(prefix+'Parent\n'+(prefix==='1. '?'2. ':'- ')+'Child');await caret('Child');await page.keyboard.press('Tab');assert.equal(await page.locator('#rich-editor li li').count(),1);await page.keyboard.type('X');assert.equal(await page.locator('#rich-editor li li').innerText(),'XChild');await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('#rich-editor li li').count(),0);assert.equal(await page.locator('#rich-editor li').count(),2);}
 await fresh('```\nAB\n```');await caret('B');await page.keyboard.press('Tab');assert.equal(await page.locator('#rich-editor pre').textContent(),'A\tB');
 await fresh('| A | B |\n| --- | --- |\n| C | D |');await caret('C');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>(getSelection().anchorNode.nodeType===3?getSelection().anchorNode.parentElement:getSelection().anchorNode).closest('td,th').textContent),'D');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>(getSelection().anchorNode.nodeType===3?getSelection().anchorNode.parentElement:getSelection().anchorNode).closest('td,th').textContent),'C');
 for(const view of ['write','split']){await fresh('AB',view);await page.evaluate(()=>editor.setSelectionRange(1,1));await page.keyboard.press('Tab');await page.keyboard.type('X');assert.equal(await source(),'A\tXB');await page.evaluate(()=>editor.setSelectionRange(0,0));await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');assert.equal(await source(),'A\tXB');}
 await fresh('One\nTwo','write');await page.keyboard.press('Control+a');await page.keyboard.press('Tab');assert.equal(await source(),'\tOne\n\tTwo');await page.keyboard.press('Control+a');await page.keyboard.press('Shift+Tab');assert.equal(await source(),'One\nTwo');
 await fresh('One\nTwo');await page.keyboard.press('Control+a');await page.keyboard.press('Tab');assert.equal(await source(),'\tOne\n\tTwo');await page.keyboard.press('Control+a');await page.keyboard.press('Shift+Tab');assert.equal(await source(),'One\nTwo');
 await fresh('```\n\tCode\n```');await caret('Code');await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('#rich-editor pre').textContent(),'Code');
 await fresh('AlphaBeta');await caret('Beta');await page.keyboard.press('Control+Shift+ArrowRight');await page.keyboard.press('Tab');assert.equal(await source(),'Alpha\t');
 await fresh('Keep');await caret('Keep');const guards=native?[{altKey:true},{isComposing:true}]:[{ctrlKey:true},{altKey:true},{metaKey:true},{isComposing:true}];assert.deepEqual(await page.evaluate(guards=>guards.map(options=>{const e=new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true,...options});rich.dispatchEvent(e);return e.defaultPrevented;}),guards),guards.map(()=>false));assert.equal(await source(),'Keep');
 // Tab in a normal UI field retains focus navigation and never edits a note.
 const uiControl=page.locator(native?'#new-note-tab':'#filename');await uiControl.focus();const unchanged=await source();await page.keyboard.press('Tab');assert.equal(await source(),unchanged);assert.equal(await uiControl.evaluate(el=>document.activeElement===el),false);
 await fresh('Persisted');await caret('Persisted');await page.keyboard.press('Tab');const expected=await source();await page.evaluate(()=>{setMode('write');setMode('rich');commitRich();});assert.equal(await source(),expected);
 if(native)await page.evaluate(()=>{persist();return flushLibrary();});else await page.evaluate(()=>persist());await page.reload();await page.waitForFunction(()=>typeof rich!=='undefined'&&rich.textContent.includes('Persisted'));assert.equal(await source(),expected);
 assert.deepEqual(errors,[]);console.log('PASS Tab: insertion/caret, Shift+Tab, Undo/Redo, styles, list nesting, code, tables, source/split, multiline selections, UI focus, view round trip and reload in '+(native?'Electron':'Edge'));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(host)await host.close();});
